### ISSUE TITLE
Client error: cannot read property querySelector of null

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-menu-bar-flow#33]
With 1.0.0.rc1 I'm getting this client error:

```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at HTMLElement.get _container [as _container] (vaadin-menu-bar-buttons-mixin.html:66)
    at HTMLElement.__renderButtons (vaadin-menu-bar-buttons-mixin.html:175)
    at HTMLElement.render (vaadin-menu-bar-buttons-mixin.html:171)
    at Object.eval (eval at qt (client-5B44EA78EA65C9AA94E2163A65E14674.cache.js:983), <anonymous>:3:139)
```

I wasn't able to replicate in a sample project, but I couldn't spot the differences between the real case and the sample. Maybe someone can help?

The `MenuBar` is placed in a slot of a `RouterLayout` and has a simple item added with `addItem(String, EventListener)`.

**Comment by pekam** [comment]
That is interesting... Some observations:
- The stack trace comes from Flow client engine, so it's the Flow component calling `render` after the items are updated.
- The error occurs because `shadowRoot` does not exist yet.
- The menu-bar's functions do exist, so the custom element is defined.
- Before calling `render`, the Flow component sets the `items`-property. This should trigger the observer, which should also call `__renderButtons`. So the error should occur already at this point.

So it seems that Polymer has not done its job yet: shadow root is not attached and observers are not registered.

Are you using Vaadin 14 already (Flow 2.0)?
If yes, are you running in npm or bower mode?
And which browser are you using?

**Comment by heruan** [comment]
Thank you @pekam for the feedback! I was able to reproduce: it happens when the `MenuBar` is added to a component which has a `PolymerTemplate` router layout, which has at least one `@Id`-mapped field.

Minimal example:

```html
<dom-module id="simple-layout">
  <template>
    <div id="header"></div>
    <div part="content">
      <slot></slot>
    </div>
  </template>

  <script>
    class SimpleLayout extends Polymer.Element {
      static get is() { return 'simple-layout'; }
      static get properties() {
        return {
        };
      }
    }

    window.customElements.define(SimpleLayout.is, SimpleLayout);
  </script>
</dom-module>
```


```java
@Tag("simple-layout")
@HtmlImport("simple-layout.html")
public class SimpleLayout extends PolymerTemplate<TemplateModel>
        implements HasComponents, RouterLayout {

    @Id
    Div header;

}

@Route(layout = SimpleLayout.class)
public class MenuBarClientError extends Div implements HasComponents {

    public MenuBarClientError() {
        var menu = new MenuBar();
        menu.addItem("Foo");
        this.add(menu);
    }

}
```

Notes:
1. removing the `@Id` annotation the client error doesn't happen;
2. it happens only if the `PolymerTemplate` is a router layout.

**Comment by pekam** [comment]
Thanks! I was able to reproduce the issue with this info.

Based on the conditions, it seems that something is not quite right in Flow, but it seems to be possible to also avoid this problem in the component implementation. I'll try to fix it soon.

**Comment by heruan** [comment]
Thank you! Might be better to fix this in Flow before 14, then! Right? Is there an issue for Flow already?

**Comment by pekam** [comment]
Unfortunately I think there are currently bigger priorities for Flow fixes before V14, if the problem occurs only with menu-bar and can be easily fixed for this component.

I'll try later if I can reproduce the issue with a simpler test component to provide a proper ticket for Flow.

My assumption is that for any Polymer component in those conditions (component inside a `PolymerTemplate/RouterLayout` which uses `@Id`), the `Page::executeJavaScript`-executions are run before the Polymer initialization logic.

**Comment by Legioth** [comment]
> My assumption is that for any Polymer component in those conditions (component inside a `PolymerTemplate/RouterLayout` which uses `@Id`), the `Page::executeJavaScript`-executions are run before the Polymer initialization logic.

Flow's client-side won't even have a reference to the element until after Polymer has created and initialized the element. There's logic in `ExecuteJavaScriptProcessor.handleInvocation(JsonArray)` which tries to wait until the element is actually available.

**Comment by pekam** [comment]
Ok, thanks for the input! Do you have any other ideas what could cause `shadowRoot` to be null and property-observers non-functional at the point of JavaScript execution?

**Comment by heruan** [comment]
Hm, I'm trying to understand all the pieces in here: seems like the culprit is the `@Id` field, since if I remove it the error doesn't happen; so, does the `@Id` annotation change the order of execution of JavaScript during layout composition?

**Comment by Legioth** [comment]
For a "regular" component, Flow itself creates the client-side DOM element and manages its full lifecycle. For `@Id` components, it's instead Polymer that creates the DOM element and Flow needs to go looking for it to be able to apply changes received from the server. Under various circumstances, Polymer only creates the element after regular processing has completed.

Because of this, Flow has special logic that waits until some specific triggers before running `executeJavaScript` for `@Id` elements. It is possible that there's some special case which causes that trigger to happen too early, thus causing the script to run before the component itself is fully initialized.

**Comment by pekam** [comment]
The weird thing is that in this case the `MenuBar` itself is not id-mapped. Adding a separate id-mapped component, which shouldn't affect the menu-bar in any way, causes the bug to occur.

So it seems that having at least one id-mapped component, versus having none, makes a difference for other components as well.

**Comment by Legioth** [comment]
With that clarification, I have a hypothesis for what goes on. The `MenuBar` element is a regular element from Flow's point of view, but it's not yet attached to the DOM because its parent is still pending actions from Polymer. This might cause `executeJavaScript` to be run before the element is actually attached. The only workaround that comes to mind then would be to use `<slot>` instead of `@Id` for handling the parent.

If this is the cause, one way of looking at this is that there's a bug in `<vaadin-menu-bar>` since its `render()` method can only be called when the element is attached. Alternatively, it can be seen as a bug in Flow that the delaying of `executeJavaScript` isn't also honoured for children of `@Id` elements. It might make sense to fix both issues since they can occur independently of each other in other use cases. In either case,`vaadin-menu-bar-flow` is most likely "innocent" even though that's where the symptoms show up.

**Comment by pekam** [comment]
> there's a bug in <vaadin-menu-bar> since its render() method can only be called when the element is attached

That is actually very true. We will fix this, ticket created: https://github.com/vaadin/vaadin-menu-bar/issues/70

> the delaying of executeJavaScript isn't also honoured for children of @Id elements

The menu-bar is actually not a child of the `@Id`-component in heruan's example.

**Comment by pekam** [comment]
Created a ticket for Flow: https://github.com/vaadin/flow/issues/5722
