### ISSUE TITLE
Prorotype menu Flow API

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-menu-bar-flow#6]
What should `menu.addItem(component)` do? Should the same component be dynamically teleported between the root level menu button and the ellipsis button dropdown menu item depending on the viewport width.

Can `menu.addItem` return a reference to the created `MenuItem` as it does with ContextMenu? In that case we'd probably need to include the whole `MenuItem` in a root level button. Looks like the web component will need to support the `component` API also.

Prototype different solutions and try to find optimal API for `menu.addItem`.

How about item checked api for menu root level items???

**Comment by pekam** [comment]
Identified problems with using the `MenuItem` and `SubMenu` APIs from `ContextMenu`:
- `MenuItem::setCheckable`
  - should not be supported for root-level items
  - in v8 the solution is to simply throw an exception
- `MenuItem::getContextMenu`
  - returns the `ContextMenu` component to which the `MenuItem` belongs
  - does not make sense for `MenuBar`
  - could just return `null` or throw an exception

One option is to introduce `RootMenuItem`, which does not extend the features of `MenuItem`. This would however introduce another problem:
- `SubMenu.getParentMenuItem` has return type `MenuItem`
  - it wouldn't work for the first sub-menu
  - changing this design might be really expensive considering the ContextMenu/SubMenu/GridContextMenu/GridSubMenu-mess
  
I suggest to just use the `SubMenu` and `MenuItem` APIs and throw on unsupported methods.
- It's clearer for the users to just use APIs familiar from `ContextMenu`, and not have a special class for the root-level items
- Even though throwing `UnsupportedOperationExceptions` implies bad design, it should be quite clear that these methods make no sense in these cases
  - also throwing on `setCheckable` is familiar from v8
- still not sure if `MenuItem::getContextMenu` should return `null` or throw

Findings about the implementation:
- The logic for generating the `items`-array for `ContextMenu` works without any changes for `MenuBar`
  - this is however private code in `ContextMenu`, so needs to be opened some way to avoid duplicating code
- Web component just needs to support rendering components on the root-level
- Since we use click-listeners on the `MenuItems` instead of an `item-selected` event, the root-level items need some special handling, as the click should be caught from the button, not just the smaller rectangle of the item component inside it
  - propagate the click-listener to the button somehow?
  - use `item-selected` internally to fire the click event for Flow?
